### ISSUE TITLE
x86-64 Support

### ISSUE THREAD

**Issue by WinterPhoenix** [RaphaelIT7/gmod-holylib#4]
This might be a pain in the ass and/or impossible, I know.

My production servers run on the x86-64 beta, which means modules need to be 64-bit to work. Trying to run holylib from Release 0.3 just gives me this:
```
LD_LIBRARY_PATH=/home/steam/gmod_yuki/bin/linux64:.:bin/linux64:linux64:
/home/steam/gmod_yuki/ghostinj.dll: wrong ELF class: ELFCLASS32
/home/steam/SGS_SRCDS_x64.sh: line 14: 1842163 Segmentation fault      ./bin/linux64/srcds $PARAMS
```

I humbly request support, if at all possible.

**Comment by RaphaelIT7** [comment]
This will take a bit, but I think I could get it done in the next few days

**Comment by RaphaelIT7** [comment]
Finally got the first 64x compile :D
https://github.com/RaphaelIT7/gmod-holylib/actions/runs/10219727684

**Comment by RaphaelIT7** [comment]
I prioritized the steamworks symbols so that you could use this since you requested those functions.

**Comment by WinterPhoenix** [comment]
Awesome, thank you! Could you trigger a build of 64-bit ghostinj for testing as well?

**Comment by RaphaelIT7** [comment]
https://github.com/RaphaelIT7/gmod-holylib/actions/runs/10221980658

**Comment by WinterPhoenix** [comment]
Using these builds:
- Ghostinj: https://github.com/RaphaelIT7/gmod-holylib/actions/runs/10221980658
- HolyLib: https://github.com/RaphaelIT7/gmod-holylib/actions/runs/10221980750

Okay, first issue is it tries to load `_linux.so` instead of `_linux64.so`:
```
--- Holylib Loading ---
Failed to open gmsv_holylib_linux.so (garrysmod/lua/bin/gmsv_holylib_linux.so: cannot open shared object file: No suc
h file or directory)
Failed to find holylib entry point (/home/steam/gmod_yuki/ghostinj.dll: undefined symbol: HolyLib_PreLoad)
--- Holylib loaded ---
```

Also funny that it says "loaded" when it didn't.

If I rename it, it starts to load stuff but I get a segfault:
```
Server will auto-restart if there is a crash.
LD_LIBRARY_PATH=/home/steam/gmod_yuki/bin/linux64:.:bin/linux64:linux64:
--- Holylib Loading ---
Registered module holylib (Enabled: true)
Registered module gameevent (Enabled: true)
Registered module serverplugin (Enabled: true)
Registered module sourcetv (Enabled: true)
Registered module threadpoolfix (Enabled: true)
Registered module stringtable (Enabled: true)
Registered module precachefix (Enabled: true)
Registered module pvs (Enabled: true)
Registered module surffix (Enabled: true)
Registered module filesystem (Enabled: true)
Registered module util (Enabled: true)
Registered module concommand (Enabled: true)
Registered module vprof (Enabled: true)
Registered module cvars (Enabled: true)
Registered module bitbuf (Enabled: true)
Registered module networking (Enabled: true)
Registered module steamworks (Enabled: true)
Registered module pas (Enabled: true)
/home/steam/SGS_SRCDS_x64.sh: line 14: 3687205 Segmentation fault      ./bin/linux64/srcds $PARAMS
```

Here's the DMP for that:
[5b5d94d7-01b1-461a-f8ea94b9-fe9b112d.zip](https://github.com/user-attachments/files/16476008/5b5d94d7-01b1-461a-f8ea94b9-fe9b112d.zip)

**Comment by RaphaelIT7** [comment]
So you can now start but level shutdown will cause a crash or it still be stuck when shutting down and I have no idea why :/
I probably have to ask rubat later to fix this crash

**Comment by RaphaelIT7** [comment]
I'll look into it today

**Comment by RaphaelIT7** [comment]
The crash on startup is fixed and I also fixed the symbol for InitLuaClasses so that the Lua API will be available as soon as possible / it won't try to use the fallback method

**Comment by RaphaelIT7** [comment]
The issue which causes the crash on level shutdown is definetly caused by ConVars :/
and being stuck when completly shutting down is caused by the `-usegh` argument / the ghostinj dll but it doesn't seem to be caused by the dll directly.

To fix the ConVar crash for now, I won't be registering them so you can't directly modify them.
And to solve the ghostinj hang, you can just not use it / it won't be required for 64x.  
It is only really used for 32x to fix the threadpool issue

**Comment by RaphaelIT7** [comment]
It could be that I have an invalid symbol somewhere

**Comment by RaphaelIT7** [comment]
If I see this correctly, when calling Shutdown, it will crash in the next few frames when without chttp.
So it could be that I got the symbol of the wrong function or the engine just can't handle it for some reason

**Comment by WinterPhoenix** [comment]
Using Build: https://github.com/RaphaelIT7/gmod-holylib/actions/runs/10580920040

Okay. I understand a little better what's going on, but I still don't have a full explanation. `steamworks.Shutdown()` will cause a segfault in my gamemode with CHTTP...but only if something tries to use the ISteamHTTP function.

`http.Fetch` and `http.Post` have a [localized HTTP function](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/modules/http.lua) by default, which means calls to those were using ISteamHTTP even though I had `HTTP = CHTTP` elsewhere.

I can effectively avoid the segfault by just overriding those to use CHTTP as well. It doesn't address whatever the root cause is, but it's a really specific set of circumstances involving the Lua state it seems...

Also, `steamworks.ForceActivate()` doesn't seem to work at all:
```
> print(steamworks.ForceActivate())...

[ERROR] lua_run:1: Failed to load SV_InitGameServerSteam!

  1. ForceActivate - [C]:-1
   2. unknown - lua_run:1
```

And `pas.TestPAS()` causes a segfault even without any other modules loaded, with the vanilla base gamemode:
```
> print(pas.TestPAS(Vector(0, 0, 128), Vector(0, 0, 256)))...
/home/steam/SGS_SRCDS_x64.sh: line 14: 860804 Segmentation fault      ./bin/linux64/srcds $PARAMS
```
DMP: [f8ce69b2-1ac6-4c0f-18fde3bd-963bc2cd.zip](https://github.com/user-attachments/files/16773617/f8ce69b2-1ac6-4c0f-18fde3bd-963bc2cd.zip)

**Comment by RaphaelIT7** [comment]
`steamworks.ForceActivate` didn't support 64x at that point but It should now.

**Comment by WinterPhoenix** [comment]
Using Build: https://github.com/RaphaelIT7/gmod-holylib/actions/runs/10682631128

So we have a new issue now, with `Player:StripWeapon`. In my gamemode it causes a segfault. In the vanilla base gamemode, it causes `Lua Error: C++ exception`.

Code to reproduce:
```
lua_run Entity(1):Give("weapon_pistol")
lua_run Entity(1):StripWeapon("weapon_pistol")
```

No issue when not loading HolyLib.

DMP: [b6bd21e8-6d4b-426c-fbf2aabb-970a2f95.zip](https://github.com/user-attachments/files/16853568/b6bd21e8-6d4b-426c-fbf2aabb-970a2f95.zip)

**Comment by RaphaelIT7** [comment]
try it with vprof off

**Comment by WinterPhoenix** [comment]
that fixed it lol

**Comment by RaphaelIT7** [comment]
I'll be fixing a bf_write function and then I'm gonna try to fix the pas crash

**Comment by RaphaelIT7** [comment]
It's a pain to get pas working on 64x :/
I can't properly get the `g_BSPData` and even when I load it manually I still get invalid data since something on 64x is different :<
(It'll probably take a good few days or even weeks. Out of curiosity, do you use 64x for servers and if so what's your decision behind it?)

**Comment by WinterPhoenix** [comment]
I run x86-64 on my production servers. It's for a few reasons, but mainly it's because if 64-bit is the future of GMod, which I will continue to act like it is regardless of Facepunch's boneheaded decisions, somebody has to test it.

Like, it's ridiculous. It's current year, nothing is 32-bit only anymore, and whole operating systems are dropping/have dropped support for it (macOS is still listed as supported on the store page, even!).

TF2's source branch is fairly close to GMod and they could take a look at that if they really are at a total loss for how to continue Willox's work on x86-64.

**Comment by RaphaelIT7** [comment]
I personally would just hope that if they switch to 64x that they still continue to support 32x dedicated servers.
64x is a huge pain for projects like this one, and It can also be a pain to maintain them, so as long as 64x server don't have debug symbols or better support like new engine interfaces / functions I wouldn't want this switch to happen if it means that 32x Servers won't be supported anymore. 
But 64x itself would open some interesting possibilities.

**Comment by RaphaelIT7** [comment]
A while ago I got pas working on 64x.
Since the last few modules now missing are a bit harder to implement and will take longer, is there one that should be prioritized?

**Comment by WinterPhoenix** [comment]
Nice! Well the two heavy hitters for me are Steamworks and PAS, so as long as those two work I’m happy.

Maybe reviving/making functional vprof on x64 if possible?

**Comment by RaphaelIT7** [comment]
Vprof in general on 64x seems weird.
I don't know why it even crashes but it seems like In gmod `VPROF_LEVEL` is set to 0 which causes most vprof calls in the engine to not even be recorded / vprof is simply disabled for almost every thing (thats why `vprof_generate_report` is so empty).
Thats just for Gmod's vprof calls. (Could probably ask Rubat about it)
HolyLibs calls crashing are still a thing that I can't figure out yet. I'll look into it tomorrow again but from what I can tell it could be that I got a symbol wrong

**Comment by RaphaelIT7** [comment]
`vprof` finally works on 64x.
I had an invalid symbol there, and the sdk itself was broken because an `unsigned int` was compared against a `unsigned long`.
Maybe that's also why vprof itself is broken. My original theory with `VPROF_LEVEL` could be wrong, so I would guess gmod has the same issue.
https://github.com/RaphaelIT7/sourcesdk-minimal/commit/a23b6e8f2e38f6605f8f8106107f5b9601ed5ec7

**Comment by WinterPhoenix** [comment]
I have two crashes for you, that started occurring after I updated from **0.8-pre** to **0.8-pre2**.

I'm not sure what causes the other one yet, so I'll just post this one for now.

### Crash 1
Running `holylib_createdebugdump` crashes a fresh SRCDS instance.
[console.log](https://github.com/user-attachments/files/23512044/console.log)
[debug.log](https://github.com/user-attachments/files/23511873/debug.log)
[8a5251b9-fb1c-4674-f472a0bc-dd87a15b.txt](https://github.com/user-attachments/files/23511875/8a5251b9-fb1c-4674-f472a0bc-dd87a15b.txt)
[8a5251b9-fb1c-4674-f472a0bc-dd87a15b.dmp](https://github.com/user-attachments/files/23511876/8a5251b9-fb1c-4674-f472a0bc-dd87a15b.dmp)

**Comment by WinterPhoenix** [comment]
New crash for you on `Release0.8-pre3`:
[crash_2026-04-11_22_24_51-0.log](https://github.com/user-attachments/files/26649988/crash_2026-04-11_22_24_51-0.log)

```
> version
Protocol version 24
Network version 2025.03.26 (garrysmod)
Exe build: 13:34:44 Apr  1 2026 (10007) (4000)
GMod version 2026.04.03, branch: x86-64
Linux 64bit Dedicated Server
```

Happens when the server exits or changelevels.

Also please note if it's relevant, my Dev server is now on Arch Linux instead of Ubuntu Server. And for some reason I don't have a core dump for this one (might be misconfigured on my end; let me know if you need it).

**Comment by RaphaelIT7** [comment]
I couldn't reproduce it on my testing server though from looking at the code the commit above may solve it

**Comment by WinterPhoenix** [comment]
No longer crashing on exit/changelevel as of 5a5c2fd

Thanks!

**Comment by RaphaelIT7** [comment]
Since x86-64 may be dropped in the future and the dev 64x will be the new target, this won't be a priority.
This probably is still is many months, if not a year away though with how long this has been taking. Starting to work on supporting dev's branch 64x build will also take a long time.

<img width="1262" height="121" alt="Image" src="https://github.com/user-attachments/assets/67caa96f-5f54-43c0-97f1-f774a0d8f538" />
